### PR TITLE
Enhance/ssl

### PR DESCRIPTION
**Pull request by yanntech**
Hi,

This PR improve the TLS configuration in nginx:

- Remove SSLv3 (Poodle)
- Add DH2048
- Switch to RSA2048
- Strong cipher list 
- Add HSTS

Regards,

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you @yanntech for this great PR. I let @nledez and @LucsT our administration system experts review it.

**Comment by jmerciercode** [comment]
:+1:

**Comment by footplus** [comment]
:+1:

**Comment by LucsT** [comment]
It's ok to merge.

Great PR

**Comment by frankrousseau** [comment]
Something went wrong while running the continuous integration script. @LucsT could you provide more details so @yanntech can help about it?

**Comment by aenario** [comment]
Hi @yanntech, we had some trouble with our continuous integration, so we had to revert your PR, #141 is the same commit and has just been merged. For good this time.

Thanks again !

**Pull request merged**
