### PR TITLE
Add check_fab command to Fabric file & update README

### PR DESCRIPTION
**Pull request by nledez**

### CODE REVIEW

**Comment by FromBabylon** [comment]
First, good idea to add a check ;-) 

Then, I think that is really a bad idea to : 
 - Enable root login. That is a serious security "issues" in the sense that every bad guys first try to ssh with root on your server. You don't need that as long as you've got a user with sudo rights 
 - Enable root login without password. I don't want to try but if you haven't enable key authentication that means anyone can access with root ! Someone confirm ? 
 - Give all users sudo. You should either allow one user or a group of users. (I don't understand the 'pi'  at the beginning of line 86, is that a group ? )

The problem is that you don't even say "Have you enabled key authentication ?". If someone has not / don't know what is it, he will then do what you suggested and expose his server. I think for a "confirm" user that should not be a problem as long as you understand what you're doing and that you fix things after fabric stuff is done. But for the newbie that wanna try things..

Why not just advice that if you're running into fabric authentication issues, log in ssh with a user that has sudo and launch fabric stuff on localhost ? Is that bad ?

And as I said in cozy forum, what makes fabric authentication issues (authentication not authentification --> line 72) is the fact that Password authentication is disabled. So, re-enable it for fabric stuff makes everything works.

**Comment by nledez** [comment]
Hello @FromBabylon,

Best practices are:
- Disable root login
- Made all commands with sudo password
- Use ssh key protected with passphrase to connect on hosts

In the sudo line, pi is the user allow to launch all commands without password. Il just test it on my Raspberryπ.

In fact, I put all methods can work. Soo, choose the right one for you.

Personally, I use ssh key on root. Root can't login remotely with password. And I'm very paranoid about my ssh key.

But it's my job to run commands as root all the day. And I can't lose time with type sudo password all the day.

I don't know if I need to add some informations about this part in documentation.

**Comment by nledez** [comment]
Any reason to not merge this one @frankrousseau?

**Comment by frankrousseau** [comment]
Ok, I can't remember why I didn't merge it earlier.

**Pull request merged**
