### PR TITLE
[fix] Download the node vanilla sources instead of "arm-pi"

### PR DESCRIPTION
**Pull request by Kloadut**
For Raspberry Pi 2 compatibility.

I will try out on an old Raspberry Pi model B to confirm the functioning

### CODE REVIEW

**Comment by Kloadut** [comment]
Actually RPi2 needs a specific treatment

**Comment by frankrousseau** [comment]
Yep and that one dowload a pre-compiled version of Node.

**Comment by frankrousseau** [comment]
Whatever I think we should drop the Pi Support. Instead here is what we should:

* Support for Pi 2
* Cozy Light for Pi 1

**Comment by aenario** [comment]
+1,  cozy really isnt usable on Pi1 anymore.

**Pull request closed without merging**
